// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

Future<void> connectToMuse({String? macAddress}) =>
    RustLib.instance.api.crateApiConnectToMuse(macAddress: macAddress);

Future<void> disconnectMuse() => RustLib.instance.api.crateApiDisconnectMuse();

Future<ConnectionStatus> getConnectionStatus() =>
    RustLib.instance.api.crateApiGetConnectionStatus();

Future<EegData> getLatestData({required int numSamples}) =>
    RustLib.instance.api.crateApiGetLatestData(numSamples: numSamples);

Future<void> initLogger() => RustLib.instance.api.crateApiInitLogger();

Future<String> verifyBrainflowVersion() =>
    RustLib.instance.api.crateApiVerifyBrainflowVersion();

Future<String> testLogging() => RustLib.instance.api.crateApiTestLogging();

enum ConnectionStatus {
  disconnected,
  connecting,
  connected,
  error,
  ;
}

class EegData {
  final Uint64List channels;
  final List<Float64List> data;

  const EegData({
    required this.channels,
    required this.data,
  });

  @override
  int get hashCode => channels.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EegData &&
          runtimeType == other.runtimeType &&
          channels == other.channels &&
          data == other.data;
}
