// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'muse_parser.dart';
import 'muse_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw);

  @protected
  EegData dco_decode_eeg_data(dynamic raw);

  @protected
  EegResolution dco_decode_eeg_resolution(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  F64Array3 dco_decode_f_64_array_3(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MusePacketType> dco_decode_list_muse_packet_type(dynamic raw);

  @protected
  List<MuseProcessedData> dco_decode_list_muse_processed_data(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  MuseModel dco_decode_muse_model(dynamic raw);

  @protected
  MusePacketType dco_decode_muse_packet_type(dynamic raw);

  @protected
  MuseProcessedData dco_decode_muse_processed_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer);

  @protected
  EegData sse_decode_eeg_data(SseDeserializer deserializer);

  @protected
  EegResolution sse_decode_eeg_resolution(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  F64Array3 sse_decode_f_64_array_3(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<MusePacketType> sse_decode_list_muse_packet_type(
      SseDeserializer deserializer);

  @protected
  List<MuseProcessedData> sse_decode_list_muse_processed_data(
      SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  MuseModel sse_decode_muse_model(SseDeserializer deserializer);

  @protected
  MusePacketType sse_decode_muse_packet_type(SseDeserializer deserializer);

  @protected
  MuseProcessedData sse_decode_muse_processed_data(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  JSAny cst_encode_eeg_data(EegData raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_usize_strict(raw.channels),
      cst_encode_list_list_prim_f_64_strict(raw.data)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_f_64_array_3(F64Array3 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return Float64List.fromList(raw).jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_f_64_strict(List<Float64List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_f_64_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_u_8_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_muse_packet_type(List<MusePacketType> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_muse_packet_type).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_muse_processed_data(List<MuseProcessedData> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_muse_processed_data).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_f_64_strict(Float64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_usize_strict(Uint64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError('Not implemented in this codec');
  }

  @protected
  JSAny cst_encode_muse_processed_data(MuseProcessedData raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_list_prim_f_64_strict(raw.eeg),
      cst_encode_list_prim_f_64_strict(raw.ppgIr),
      cst_encode_list_prim_f_64_strict(raw.ppgRed),
      cst_encode_list_prim_f_64_strict(raw.ppgNir),
      cst_encode_opt_box_autoadd_f_64(raw.spo2),
      cst_encode_opt_box_autoadd_f_64(raw.fnirsHbo2),
      cst_encode_opt_box_autoadd_f_64(raw.fnirsHbr),
      cst_encode_opt_box_autoadd_f_64(raw.fnirsTsi),
      cst_encode_f_64_array_3(raw.accel),
      cst_encode_f_64_array_3(raw.gyro),
      cst_encode_f_64(raw.timestamp),
      cst_encode_f_64(raw.battery),
      cst_encode_list_muse_packet_type(raw.packetTypes)
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_connection_status(ConnectionStatus raw);

  @protected
  int cst_encode_eeg_resolution(EegResolution raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_muse_model(MuseModel raw);

  @protected
  int cst_encode_muse_packet_type(MusePacketType raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_connection_status(
      ConnectionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_eeg_data(EegData self, SseSerializer serializer);

  @protected
  void sse_encode_eeg_resolution(EegResolution self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64_array_3(F64Array3 self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_f_64_strict(
      List<Float64List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_muse_packet_type(
      List<MusePacketType> self, SseSerializer serializer);

  @protected
  void sse_encode_list_muse_processed_data(
      List<MuseProcessedData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_usize_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_muse_model(MuseModel self, SseSerializer serializer);

  @protected
  void sse_encode_muse_packet_type(
      MusePacketType self, SseSerializer serializer);

  @protected
  void sse_encode_muse_processed_data(
      MuseProcessedData self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__connect_to_muse(
          NativePortType port_, String? mac_address) =>
      wasmModule.wire__crate__api__connect_to_muse(port_, mac_address);

  void wire__crate__api__disconnect_muse(NativePortType port_) =>
      wasmModule.wire__crate__api__disconnect_muse(port_);

  void wire__crate__muse_types__eeg_resolution_offset(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__eeg_resolution_offset(port_, that);

  void wire__crate__muse_types__eeg_resolution_scale_factor(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__eeg_resolution_scale_factor(
          port_, that);

  void wire__crate__api__get_connection_status(NativePortType port_) =>
      wasmModule.wire__crate__api__get_connection_status(port_);

  void wire__crate__api__get_latest_data(
          NativePortType port_, int num_samples) =>
      wasmModule.wire__crate__api__get_latest_data(port_, num_samples);

  void wire__crate__muse_parser__get_muse_model_from_name(
          NativePortType port_, String name) =>
      wasmModule.wire__crate__muse_parser__get_muse_model_from_name(
          port_, name);

  void wire__crate__api__init_logger(NativePortType port_) =>
      wasmModule.wire__crate__api__init_logger(port_);

  void wire__crate__muse_parser__init_muse_parser(
          NativePortType port_, int model) =>
      wasmModule.wire__crate__muse_parser__init_muse_parser(port_, model);

  void wire__crate__muse_types__muse_model_channel_count(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__muse_model_channel_count(port_, that);

  void wire__crate__muse_types__muse_model_has_fnirs(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__muse_model_has_fnirs(port_, that);

  void wire__crate__muse_types__muse_model_has_ppg(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__muse_model_has_ppg(port_, that);

  void wire__crate__muse_types__muse_model_ppg_channel_count(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__muse_model_ppg_channel_count(
          port_, that);

  void wire__crate__muse_types__muse_model_resolution(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__muse_types__muse_model_resolution(port_, that);

  void wire__crate__muse_types__muse_processed_data_default(
          NativePortType port_) =>
      wasmModule.wire__crate__muse_types__muse_processed_data_default(port_);

  void wire__crate__muse_parser__parse_and_process_muse_packets(
          NativePortType port_, JSAny raw_packets) =>
      wasmModule.wire__crate__muse_parser__parse_and_process_muse_packets(
          port_, raw_packets);

  void wire__crate__muse_parser__parse_muse_packet(
          NativePortType port_, int channel, JSAny data) =>
      wasmModule.wire__crate__muse_parser__parse_muse_packet(
          port_, channel, data);

  void wire__crate__muse_parser__send_muse_command(
          NativePortType port_, String command) =>
      wasmModule.wire__crate__muse_parser__send_muse_command(port_, command);

  void wire__crate__api__test_output(NativePortType port_) =>
      wasmModule.wire__crate__api__test_output(port_);

  void wire__crate__api__verify_brainflow_version(NativePortType port_) =>
      wasmModule.wire__crate__api__verify_brainflow_version(port_);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__connect_to_muse(
      NativePortType port_, String? mac_address);

  external void wire__crate__api__disconnect_muse(NativePortType port_);

  external void wire__crate__muse_types__eeg_resolution_offset(
      NativePortType port_, int that);

  external void wire__crate__muse_types__eeg_resolution_scale_factor(
      NativePortType port_, int that);

  external void wire__crate__api__get_connection_status(NativePortType port_);

  external void wire__crate__api__get_latest_data(
      NativePortType port_, int num_samples);

  external void wire__crate__muse_parser__get_muse_model_from_name(
      NativePortType port_, String name);

  external void wire__crate__api__init_logger(NativePortType port_);

  external void wire__crate__muse_parser__init_muse_parser(
      NativePortType port_, int model);

  external void wire__crate__muse_types__muse_model_channel_count(
      NativePortType port_, int that);

  external void wire__crate__muse_types__muse_model_has_fnirs(
      NativePortType port_, int that);

  external void wire__crate__muse_types__muse_model_has_ppg(
      NativePortType port_, int that);

  external void wire__crate__muse_types__muse_model_ppg_channel_count(
      NativePortType port_, int that);

  external void wire__crate__muse_types__muse_model_resolution(
      NativePortType port_, int that);

  external void wire__crate__muse_types__muse_processed_data_default(
      NativePortType port_);

  external void wire__crate__muse_parser__parse_and_process_muse_packets(
      NativePortType port_, JSAny raw_packets);

  external void wire__crate__muse_parser__parse_muse_packet(
      NativePortType port_, int channel, JSAny data);

  external void wire__crate__muse_parser__send_muse_command(
      NativePortType port_, String command);

  external void wire__crate__api__test_output(NativePortType port_);

  external void wire__crate__api__verify_brainflow_version(
      NativePortType port_);
}
