// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'muse_parser.dart';
import 'muse_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 859919898;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_fl_muse_brainflow_mvp',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiConnectToMuse({String? macAddress});

  Future<String> crateApiDisconnectMuse();

  Future<double> crateMuseTypesEegResolutionOffset(
      {required EegResolution that});

  Future<double> crateMuseTypesEegResolutionScaleFactor(
      {required EegResolution that});

  Future<ConnectionStatus> crateApiGetConnectionStatus();

  Future<EegData> crateApiGetLatestData({required int numSamples});

  Future<MuseModel> crateMuseParserGetMuseModelFromName({required String name});

  Future<void> crateApiInitLogger();

  Future<void> crateMuseParserInitMuseParser({required MuseModel model});

  Future<BigInt> crateMuseTypesMuseModelChannelCount({required MuseModel that});

  Future<bool> crateMuseTypesMuseModelHasFnirs({required MuseModel that});

  Future<bool> crateMuseTypesMuseModelHasPpg({required MuseModel that});

  Future<BigInt> crateMuseTypesMuseModelPpgChannelCount(
      {required MuseModel that});

  Future<EegResolution> crateMuseTypesMuseModelResolution(
      {required MuseModel that});

  Future<MuseProcessedData> crateMuseTypesMuseProcessedDataDefault();

  Future<List<MuseProcessedData>> crateMuseParserParseAndProcessMusePackets(
      {required List<Uint8List> rawPackets});

  Future<List<MuseProcessedData>> crateMuseParserParseMusePacket(
      {required int channel, required List<int> data});

  Future<Uint8List> crateMuseParserSendMuseCommand({required String command});

  Future<String> crateApiTestOutput();

  Future<String> crateApiVerifyBrainflowVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiConnectToMuse({String? macAddress}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_opt_String(macAddress);
        return wire.wire__crate__api__connect_to_muse(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiConnectToMuseConstMeta,
      argValues: [macAddress],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConnectToMuseConstMeta => const TaskConstMeta(
        debugName: "connect_to_muse",
        argNames: ["macAddress"],
      );

  @override
  Future<String> crateApiDisconnectMuse() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__disconnect_muse(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiDisconnectMuseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDisconnectMuseConstMeta => const TaskConstMeta(
        debugName: "disconnect_muse",
        argNames: [],
      );

  @override
  Future<double> crateMuseTypesEegResolutionOffset(
      {required EegResolution that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_eeg_resolution(that);
        return wire.wire__crate__muse_types__eeg_resolution_offset(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesEegResolutionOffsetConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesEegResolutionOffsetConstMeta =>
      const TaskConstMeta(
        debugName: "eeg_resolution_offset",
        argNames: ["that"],
      );

  @override
  Future<double> crateMuseTypesEegResolutionScaleFactor(
      {required EegResolution that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_eeg_resolution(that);
        return wire.wire__crate__muse_types__eeg_resolution_scale_factor(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesEegResolutionScaleFactorConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesEegResolutionScaleFactorConstMeta =>
      const TaskConstMeta(
        debugName: "eeg_resolution_scale_factor",
        argNames: ["that"],
      );

  @override
  Future<ConnectionStatus> crateApiGetConnectionStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__get_connection_status(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_connection_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetConnectionStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetConnectionStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_connection_status",
        argNames: [],
      );

  @override
  Future<EegData> crateApiGetLatestData({required int numSamples}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_i_32(numSamples);
        return wire.wire__crate__api__get_latest_data(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_eeg_data,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetLatestDataConstMeta,
      argValues: [numSamples],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLatestDataConstMeta => const TaskConstMeta(
        debugName: "get_latest_data",
        argNames: ["numSamples"],
      );

  @override
  Future<MuseModel> crateMuseParserGetMuseModelFromName(
      {required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(name);
        return wire.wire__crate__muse_parser__get_muse_model_from_name(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_muse_model,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseParserGetMuseModelFromNameConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseParserGetMuseModelFromNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_muse_model_from_name",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiInitLogger() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__init_logger(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitLoggerConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoggerConstMeta => const TaskConstMeta(
        debugName: "init_logger",
        argNames: [],
      );

  @override
  Future<void> crateMuseParserInitMuseParser({required MuseModel model}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(model);
        return wire.wire__crate__muse_parser__init_muse_parser(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseParserInitMuseParserConstMeta,
      argValues: [model],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseParserInitMuseParserConstMeta =>
      const TaskConstMeta(
        debugName: "init_muse_parser",
        argNames: ["model"],
      );

  @override
  Future<BigInt> crateMuseTypesMuseModelChannelCount(
      {required MuseModel that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(that);
        return wire.wire__crate__muse_types__muse_model_channel_count(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseModelChannelCountConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseModelChannelCountConstMeta =>
      const TaskConstMeta(
        debugName: "muse_model_channel_count",
        argNames: ["that"],
      );

  @override
  Future<bool> crateMuseTypesMuseModelHasFnirs({required MuseModel that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(that);
        return wire.wire__crate__muse_types__muse_model_has_fnirs(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseModelHasFnirsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseModelHasFnirsConstMeta =>
      const TaskConstMeta(
        debugName: "muse_model_has_fnirs",
        argNames: ["that"],
      );

  @override
  Future<bool> crateMuseTypesMuseModelHasPpg({required MuseModel that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(that);
        return wire.wire__crate__muse_types__muse_model_has_ppg(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseModelHasPpgConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseModelHasPpgConstMeta =>
      const TaskConstMeta(
        debugName: "muse_model_has_ppg",
        argNames: ["that"],
      );

  @override
  Future<BigInt> crateMuseTypesMuseModelPpgChannelCount(
      {required MuseModel that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(that);
        return wire.wire__crate__muse_types__muse_model_ppg_channel_count(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseModelPpgChannelCountConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseModelPpgChannelCountConstMeta =>
      const TaskConstMeta(
        debugName: "muse_model_ppg_channel_count",
        argNames: ["that"],
      );

  @override
  Future<EegResolution> crateMuseTypesMuseModelResolution(
      {required MuseModel that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_muse_model(that);
        return wire.wire__crate__muse_types__muse_model_resolution(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_eeg_resolution,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseModelResolutionConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseModelResolutionConstMeta =>
      const TaskConstMeta(
        debugName: "muse_model_resolution",
        argNames: ["that"],
      );

  @override
  Future<MuseProcessedData> crateMuseTypesMuseProcessedDataDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__muse_types__muse_processed_data_default(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_muse_processed_data,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseTypesMuseProcessedDataDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseTypesMuseProcessedDataDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "muse_processed_data_default",
        argNames: [],
      );

  @override
  Future<List<MuseProcessedData>> crateMuseParserParseAndProcessMusePackets(
      {required List<Uint8List> rawPackets}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_list_prim_u_8_strict(rawPackets);
        return wire.wire__crate__muse_parser__parse_and_process_muse_packets(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_muse_processed_data,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseParserParseAndProcessMusePacketsConstMeta,
      argValues: [rawPackets],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseParserParseAndProcessMusePacketsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_and_process_muse_packets",
        argNames: ["rawPackets"],
      );

  @override
  Future<List<MuseProcessedData>> crateMuseParserParseMusePacket(
      {required int channel, required List<int> data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_i_32(channel);
        var arg1 = cst_encode_list_prim_u_8_loose(data);
        return wire.wire__crate__muse_parser__parse_muse_packet(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_muse_processed_data,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseParserParseMusePacketConstMeta,
      argValues: [channel, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseParserParseMusePacketConstMeta =>
      const TaskConstMeta(
        debugName: "parse_muse_packet",
        argNames: ["channel", "data"],
      );

  @override
  Future<Uint8List> crateMuseParserSendMuseCommand({required String command}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(command);
        return wire.wire__crate__muse_parser__send_muse_command(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateMuseParserSendMuseCommandConstMeta,
      argValues: [command],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateMuseParserSendMuseCommandConstMeta =>
      const TaskConstMeta(
        debugName: "send_muse_command",
        argNames: ["command"],
      );

  @override
  Future<String> crateApiTestOutput() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__test_output(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTestOutputConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTestOutputConstMeta => const TaskConstMeta(
        debugName: "test_output",
        argNames: [],
      );

  @override
  Future<String> crateApiVerifyBrainflowVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__verify_brainflow_version(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiVerifyBrainflowVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVerifyBrainflowVersionConstMeta =>
      const TaskConstMeta(
        debugName: "verify_brainflow_version",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatus.values[raw as int];
  }

  @protected
  EegData dco_decode_eeg_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EegData(
      channels: dco_decode_list_prim_usize_strict(arr[0]),
      data: dco_decode_list_list_prim_f_64_strict(arr[1]),
    );
  }

  @protected
  EegResolution dco_decode_eeg_resolution(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EegResolution.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  F64Array3 dco_decode_f_64_array_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return F64Array3(dco_decode_list_prim_f_64_strict(raw));
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_64_strict)
        .toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<MusePacketType> dco_decode_list_muse_packet_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_muse_packet_type).toList();
  }

  @protected
  List<MuseProcessedData> dco_decode_list_muse_processed_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_muse_processed_data).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  MuseModel dco_decode_muse_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MuseModel.values[raw as int];
  }

  @protected
  MusePacketType dco_decode_muse_packet_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MusePacketType.values[raw as int];
  }

  @protected
  MuseProcessedData dco_decode_muse_processed_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return MuseProcessedData(
      eeg: dco_decode_list_list_prim_f_64_strict(arr[0]),
      ppgIr: dco_decode_list_prim_f_64_strict(arr[1]),
      ppgRed: dco_decode_list_prim_f_64_strict(arr[2]),
      ppgNir: dco_decode_list_prim_f_64_strict(arr[3]),
      spo2: dco_decode_opt_box_autoadd_f_64(arr[4]),
      fnirsHbo2: dco_decode_opt_box_autoadd_f_64(arr[5]),
      fnirsHbr: dco_decode_opt_box_autoadd_f_64(arr[6]),
      fnirsTsi: dco_decode_opt_box_autoadd_f_64(arr[7]),
      accel: dco_decode_f_64_array_3(arr[8]),
      gyro: dco_decode_f_64_array_3(arr[9]),
      timestamp: dco_decode_f_64(arr[10]),
      battery: dco_decode_f_64(arr[11]),
      packetTypes: dco_decode_list_muse_packet_type(arr[12]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionStatus.values[inner];
  }

  @protected
  EegData sse_decode_eeg_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channels = sse_decode_list_prim_usize_strict(deserializer);
    var var_data = sse_decode_list_list_prim_f_64_strict(deserializer);
    return EegData(channels: var_channels, data: var_data);
  }

  @protected
  EegResolution sse_decode_eeg_resolution(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EegResolution.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  F64Array3 sse_decode_f_64_array_3(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_f_64_strict(deserializer);
    return F64Array3(inner);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float64List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_64_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<MusePacketType> sse_decode_list_muse_packet_type(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MusePacketType>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_muse_packet_type(deserializer));
    }
    return ans_;
  }

  @protected
  List<MuseProcessedData> sse_decode_list_muse_processed_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MuseProcessedData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_muse_processed_data(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  MuseModel sse_decode_muse_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MuseModel.values[inner];
  }

  @protected
  MusePacketType sse_decode_muse_packet_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MusePacketType.values[inner];
  }

  @protected
  MuseProcessedData sse_decode_muse_processed_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eeg = sse_decode_list_list_prim_f_64_strict(deserializer);
    var var_ppgIr = sse_decode_list_prim_f_64_strict(deserializer);
    var var_ppgRed = sse_decode_list_prim_f_64_strict(deserializer);
    var var_ppgNir = sse_decode_list_prim_f_64_strict(deserializer);
    var var_spo2 = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fnirsHbo2 = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fnirsHbr = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fnirsTsi = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_accel = sse_decode_f_64_array_3(deserializer);
    var var_gyro = sse_decode_f_64_array_3(deserializer);
    var var_timestamp = sse_decode_f_64(deserializer);
    var var_battery = sse_decode_f_64(deserializer);
    var var_packetTypes = sse_decode_list_muse_packet_type(deserializer);
    return MuseProcessedData(
        eeg: var_eeg,
        ppgIr: var_ppgIr,
        ppgRed: var_ppgRed,
        ppgNir: var_ppgNir,
        spo2: var_spo2,
        fnirsHbo2: var_fnirsHbo2,
        fnirsHbr: var_fnirsHbr,
        fnirsTsi: var_fnirsTsi,
        accel: var_accel,
        gyro: var_gyro,
        timestamp: var_timestamp,
        battery: var_battery,
        packetTypes: var_packetTypes);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_connection_status(ConnectionStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_eeg_resolution(EegResolution raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_muse_model(MuseModel raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_muse_packet_type(MusePacketType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_connection_status(
      ConnectionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_eeg_data(EegData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_usize_strict(self.channels, serializer);
    sse_encode_list_list_prim_f_64_strict(self.data, serializer);
  }

  @protected
  void sse_encode_eeg_resolution(EegResolution self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_f_64_array_3(F64Array3 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_list_prim_f_64_strict(
      List<Float64List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_64_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_muse_packet_type(
      List<MusePacketType> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_muse_packet_type(item, serializer);
    }
  }

  @protected
  void sse_encode_list_muse_processed_data(
      List<MuseProcessedData> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_muse_processed_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
      Uint64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_muse_model(MuseModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_muse_packet_type(
      MusePacketType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_muse_processed_data(
      MuseProcessedData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_list_prim_f_64_strict(self.eeg, serializer);
    sse_encode_list_prim_f_64_strict(self.ppgIr, serializer);
    sse_encode_list_prim_f_64_strict(self.ppgRed, serializer);
    sse_encode_list_prim_f_64_strict(self.ppgNir, serializer);
    sse_encode_opt_box_autoadd_f_64(self.spo2, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fnirsHbo2, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fnirsHbr, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fnirsTsi, serializer);
    sse_encode_f_64_array_3(self.accel, serializer);
    sse_encode_f_64_array_3(self.gyro, serializer);
    sse_encode_f_64(self.timestamp, serializer);
    sse_encode_f_64(self.battery, serializer);
    sse_encode_list_muse_packet_type(self.packetTypes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
