// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'muse_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `unpack_eeg_ppg_packet`, `unpack_imu_packet`

Future<List<MuseProcessedData>> parseAndProcessMusePackets(
        {required List<Uint8List> rawPackets}) =>
    RustLib.instance.api
        .crateMuseParserParseAndProcessMusePackets(rawPackets: rawPackets);
