// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

enum MusePacketType {
  eegPpg,
  imu,
  other,
  ;
}

class MuseProcessedData {
  /// 7 channels × samples (in µV after BrainFlow scaling)
  final List<Float64List> eeg;

  /// Infrared PPG (for HR + SpO2)
  final Float64List ppgIr;

  /// Red PPG
  final Float64List ppgRed;

  /// Calculated SpO2 (null until enough samples)
  final double? spo2;

  /// Accelerometer [x, y, z] in g
  final F64Array3 accel;

  /// Gyroscope [x, y, z] in deg/s
  final F64Array3 gyro;

  /// Corrected timestamp (seconds since UNIX epoch)
  final double timestamp;

  /// Battery % (0-100)
  final double battery;

  /// Which packet types were in this batch
  final List<MusePacketType> packetTypes;

  const MuseProcessedData({
    required this.eeg,
    required this.ppgIr,
    required this.ppgRed,
    this.spo2,
    required this.accel,
    required this.gyro,
    required this.timestamp,
    required this.battery,
    required this.packetTypes,
  });

  static Future<MuseProcessedData> default_() =>
      RustLib.instance.api.crateMuseTypesMuseProcessedDataDefault();

  @override
  int get hashCode =>
      eeg.hashCode ^
      ppgIr.hashCode ^
      ppgRed.hashCode ^
      spo2.hashCode ^
      accel.hashCode ^
      gyro.hashCode ^
      timestamp.hashCode ^
      battery.hashCode ^
      packetTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MuseProcessedData &&
          runtimeType == other.runtimeType &&
          eeg == other.eeg &&
          ppgIr == other.ppgIr &&
          ppgRed == other.ppgRed &&
          spo2 == other.spo2 &&
          accel == other.accel &&
          gyro == other.gyro &&
          timestamp == other.timestamp &&
          battery == other.battery &&
          packetTypes == other.packetTypes;
}
